version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwordPG
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    image: backend:0.1
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:passwordPG@db:5432/ProdPlanDB
volumes:
  postgres:
